# -*- coding: utf-8 -*-
"""bmw_sales_global_deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OenAcExTycI0hp4SBVL6pJ9bWZO4fbkD
"""

import streamlit as st
import pandas as pd
import joblib

# Load trained model
model = joblib.load("XGBoost_model.pkl")

st.title("BMW Sales Prediction System")

st.write("Enter the details below to predict sales category")

# User Inputs
Year = st.number_input("Year")
Month = st.number_input("Month")
Avg_Price_EUR = st.number_input("Average Price (EUR)")
Revenue_EUR = st.number_input("Revenue (EUR)")
BEV_Share = st.number_input("BEV Share")
Premium_Share = st.number_input("Premium Share")
GDP_Growth = st.number_input("GDP Growth")
Fuel_Price_Index = st.number_input("Fuel Price Index")

# Create dataframe for prediction
input_data = pd.DataFrame({
    'Year':[Year],
    'Month':[Month],
    'Avg_Price_EUR':[Avg_Price_EUR],
    'Revenue_EUR':[Revenue_EUR],
    'BEV_Share':[BEV_Share],
    'Premium_Share':[Premium_Share],
    'GDP_Growth':[GDP_Growth],
    'Fuel_Price_Index':[Fuel_Price_Index]
})

# Prediction
if st.button("Predict"):

    prediction = model.predict(input_data)

    if prediction[0] == 1:
        st.success("High Sales Expected")
    else:
        st.error("Low Sales Expected")